{{- if .Values.networkpolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "curity.fullname" . }}-network-policy-allow-web
spec:
  podSelector:
    matchLabels:
      role: {{ include "curity.fullname" . }}-admin
  policyTypes:
    - Ingress
  ingress:
    - {}
{{- end }}
