{{- if .Values.networkpolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "curity.fullname" . }}-network-policy
spec:
  podSelector:
    matchLabels:
      role: {{ include "curity.fullname" . }}-admin
  policyTypes:
    - Ingress
  {{- if .Values.networkpolicy.database.enabled }}
    - Egress
  {{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: {{ include "curity.fullname" . }}-runtime
      ports:
        - protocol: TCP
          port: {{ .Values.curity.admin.service.port }}
  {{- if .Values.networkpolicy.database.enabled }}
  egress:
    - to
    {{- range .Values.networkpolicy.database.cidr }}
      - ipBlock:
          cidr: {{ . }}
    {{- end }}
    {{- range .Values.networkpolicy.database.ports }}
      ports:
        - protocol: TCP
          port: {{ . }}
    {{- end }}
  {{- end }}
{{- if .Values.networkpolicy.database.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "curity.fullname" . }}-network-policy-runtime
spec:
  podSelector:
    matchLabels:
      role: {{ include "curity.fullname" . }}-runtime
  policyTypes:
    - Egress
  egress:
    - to:
    {{- range .Values.networkpolicy.database.cidr }}
      - ipBlock:
          cidr: {{ . }}
    {{- end }}
    {{- range .Values.networkpolicy.database.ports }}
      ports:
        - protocol: TCP
          port: {{ . }}
    {{- end }}
{{- end }}
{{- end }}
