apiVersion: v1
kind: Service
metadata:
  name: {{ include "curity.fullname" . }}-runtime-svc
  labels:
    {{- include "curity.labels" . | nindent 4 }}
    role: {{ include "curity.fullname" . }}-runtime
spec:
  type: {{ .Values.curity.runtime.service.type }}
  ports:
    - port: {{ .Values.curity.runtime.service.port }}
      targetPort: http-port
      protocol: TCP
      name: http-port
    - port: {{ .Values.curity.healthCheckPort }}
      targetPort: health-check
      protocol: TCP
      name: health-check
    - port:  {{ include "curity.metricsPort" . }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "curity.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: {{ include "curity.fullname" . }}-runtime
